openapi: 3.0.0
info:
  title: Private data processing API
  version: 1.0.0
servers:
  - url: https://nitro-app-nine.vercel.app/
paths:
  /:
    post:
      summary: Takes in a string and appends some text to it
      operartionId: customOperationId
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  type: string
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  nitro:
                    type: string
